// kyuubi-server/web-ui/src/app/app.component.ts
/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component } from '@angular/core';
import { fromEvent, merge } from 'rxjs';
import { map, startWith } from 'rxjs/operators';

import { StatusService } from 'services';

@Component({
  selector: 'kyuubi-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.less']
})
export class AppComponent {
  collapsed = false;
  visible = false;
  online$ = merge(
    fromEvent(window, 'offline').pipe(map(() => false)),
    fromEvent(window, 'online').pipe(map(() => true))
  ).pipe(startWith(true));

  showMessage(): void {
    if (this.statusService.listOfErrorMessage.length) {
      this.visible = true;
    }
  }

  clearMessage(): void {
    this.statusService.listOfErrorMessage = [];
    this.visible = false;
  }

  toggleCollapse(): void {
    this.collapsed = !this.collapsed;
  }

  constructor(public statusService: StatusService) {}
}

<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements.  See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership.  The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License.  You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->
<nz-layout>
  <nz-sider nzCollapsible [(nzCollapsed)]="collapsed" [nzTrigger]="null" [nzWidth]="256">
    <div class="logo">
      <a href="#/">
        <img src="assets/images/kyuubi.png" />
        <h1>Apache Kyuubi Dashboard</h1>
      </a>
    </div>
    <ul nz-menu [nzTheme]="'dark'" [nzMode]="'inline'" [nzInlineCollapsed]="collapsed" class="menu">
      <li nz-menu-item routerLinkActive="ant-menu-item-selected" [routerLink]="['/overview']">
        <span>
          <i nz-icon nzType="dashboard"></i>
          <span>Overview</span>
        </span>
      </li>
      <li nz-submenu [nzOpen]="true">
        <span title>
          <i nz-icon nzType="bars"></i>
          <span>Workload</span>
        </span>
        <ul>
          <li
            nz-menu-item
            routerLinkActive="ant-menu-item-selected"
            [routerLink]="['/job/running']"
          >
            <span>
              <i nz-icon nzType="play-circle"></i>
              <span>Analysis</span>
            </span>
          </li>
          <li
            nz-menu-item
            routerLinkActive="ant-menu-item-selected"
            [routerLink]="['/job/completed']"
          >
            <span>
              <i nz-icon nzType="check-circle"></i>
              <span>Queue</span>
            </span>
          </li>
          <li
            nz-menu-item
            routerLinkActive="ant-menu-item-selected"
            [routerLink]="['/job/completed']"
          >
            <span>
              <i nz-icon nzType="check-circle"></i>
              <span>Session</span>
            </span>
          </li>
          <li
            nz-menu-item
            routerLinkActive="ant-menu-item-selected"
            [routerLink]="['/job/completed']"
          >
            <span>
              <i nz-icon nzType="check-circle"></i>
              <span>Query</span>
            </span>
          </li>
        </ul>
      </li>
      <li nz-submenu [nzOpen]="false">
        <span title>
          <i nz-icon nzType="bars"></i>
          <span>Operation</span>
        </span>
        <ul>
          <li
            nz-menu-item
            routerLinkActive="ant-menu-item-selected"
            [routerLink]="['/job/running']"
          >
            <span>
              <i nz-icon nzType="play-circle"></i>
              <span>Running Jobs</span>
            </span>
          </li>
          <li
            nz-menu-item
            routerLinkActive="ant-menu-item-selected"
            [routerLink]="['/job/completed']"
          >
            <span>
              <i nz-icon nzType="check-circle"></i>
              <span>Completed Jobs</span>
            </span>
          </li>
        </ul>
      </li>
      <li nz-menu-item routerLinkActive="ant-menu-item-selected" [routerLink]="['/task-manager']">
        <span>
          <i nz-icon nzType="schedule"></i>
          <span>Contact Us</span>
        </span>
      </li>
    </ul>
  </nz-sider>
  <nz-layout>
    <nz-header>
      <i
        class="trigger"
        nz-icon
        [nzType]="collapsed ? 'menu-unfold' : 'menu-fold'"
        (click)="toggleCollapse()"
      ></i>
      <div class="right">
        <nz-divider nzType="vertical"></nz-divider>
        <nz-divider nzType="vertical"></nz-divider>
        <span [hidden]="online$ | async">
          <strong class="offline">Lost Connection, Reconnecting Now...</strong>
        </span>
      </div>
    </nz-header>
    <nz-content>
      <router-outlet></router-outlet>
    </nz-content>
  </nz-layout>
</nz-layout>

<nz-drawer
  [nzVisible]="visible"
  [nzWidth]="500"
  nzPlacement="right"
  nzTitle="Server Response Message List"
  (nzOnClose)="clearMessage()"
></nz-drawer>

// kyuubi-server/web-ui/src/App.vue
/* * Licensed to the Apache Software Foundation (ASF) under one or more *
contributor license agreements. See the NOTICE file distributed with * this work
for additional information regarding copyright ownership. * The ASF licenses
this file to You under the Apache License, Version 2.0 * (the "License"); you
may not use this file except in compliance with * the License. You may obtain a
copy of the License at * * http://www.apache.org/licenses/LICENSE-2.0 * * Unless
required by applicable law or agreed to in writing, software * distributed under
the License is distributed on an "AS IS" BASIS, * WITHOUT WARRANTIES OR
CONDITIONS OF ANY KIND, either express or implied. * See the License for the
specific language governing permissions and * limitations under the License. */

<script lang="ts" setup>
  // This starter template is using Vue 3 <script setup> SFCs
</script>

<template>
  <router-view />
</template>

<style scoped></style>
